apiVersion: apps/v1
kind: Deployment
metadata:
  name: facebook
spec:
  replicas: 10
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: facebook
spec:
  type: ClusterIP
  selector:
    app: devops
  ports:
  - port: 80
    targetPort: 80
